x-resume-image: &resume-image liaozhiming/django_resume:latest
x-nginx-image: &nginx-image nginx:1.21.0

version: '3.7'

services:
  resume:
    image: *resume-image
    command: gunicorn django_resume.wsgi:application --workers 3 --bind :8000
    env_file:
      - ./config/.env
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - data_static:/opt/app/static
      - data_static:/opt/app/media
      
  web:
    depends_on:
      - resume
    image: *nginx-image
    ports:
      - "80:80"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      # - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./config/resume_nginx.conf:/etc/nginx/conf.d/resume_nginx.conf
      # - /d/PyCharm/django_resume/django_resume/config/resume_nginx.conf:/etc/nginx/nginx.conf
      - data_nginx_log:/var/log/nginx
      - data_static:/opt/app/static/
      - data_media:/opt/app/media

volumes:
  data_static:
  data_nginx_log:
  data_media:
